### PR TITLE
fix for gh333: Layout broken after installation of 1.5.2

### LINKED ISSUE #333: Layout broken after installation of 1.5.2
After installation of 1.5.2 the layout is completely broken.
Looks like the theme is not working as expected.
I Found one error and fixed it: https://github.com/computersalat/hotelcommerce/commit/9d028d70c3d816328c654df14c2ef48999684eb5

I also found a lot of code changes `back to PrestaShop`: https://github.com/computersalat/hotelcommerce/commit/b2f6dd693c09656da7df63f24c70addd6ccd4708

But the front-end still looks devastated.
Someone needs to do a test install and verify

### PR DESCRIPTION
**Pull request by computersalat**
- themes/hotel-reservation-theme/header.tpl: fix href
- fix .htaccess files
fixes #333

### CODE REVIEW

**Comment by shreesh-webkul** [comment]
The issue linked with this PR #333 is still not recreated, that issue might have occurred due to some other reason 
Meanwhile, this PR is resolving another issue so it needs some changes before merging into QloApps.
The PR addresses the new configuration directives used in apache 2.4 and updates the google fonts access protocol so please update the title accordingly.
Also, unlink the PR with issue #333.

#### Changes : 
- .htaccess should use mod_authz_host instead of mod_access_compat as mod_access_compat has been depricated
  - Preferably like:

        <IfVersion < 2.4>
            Order deny,allow
            Deny from all
        </IfVersion>
        <IfVersion >= 2.4>
            <IfModule mod_authz_host.c>
                Require all denied
            </IfModule>
            <IfModule !mod_authz_host.c>
                Order deny,allow
                Deny from all
            </IfModule>
        </IfVersion>


- we have used php_flag engine off, instead we should not use this as it destroy the whole purpose of redirection using index.php, should be removed from `/img/cms/` and `/upload/` directory

**Comment by shreesh-webkul** [comment]
@computersalat 
The issue was recreated in openSUSE 15.3.
Update the given changes so that we can merge PR.

**Changes**
.htaccess should use mod_authz_host instead of mod_access_compat as mod_access_compat has been deprecated.
Apache version comparison is not required as the module can define which method to use. Only use the following code:
```
<IfModule mod_authz_host.c>
    Require all denied
</IfModule>
<IfModule !mod_authz_host.c>
    Order deny,allow
    Deny from all
</IfModule>
```

**Comment by computersalat** [comment]
> @computersalat The issue was recreated in openSUSE 15.3. Update the given changes so that we can merge PR.
> 
> **Changes** .htaccess should use mod_authz_host instead of mod_access_compat as mod_access_compat has been deprecated. Apache version comparison is not required as the module can define which method to use. Only use the following code:
> 
> ```
> <IfModule mod_authz_host.c>
>     Require all denied
> </IfModule>
> <IfModule !mod_authz_host.c>
>     Order deny,allow
>     Deny from all
> </IfModule>
> ```

Sorry, but your proposal is just **_wrong_**. You did definitly **_NOT_** understand the **_migration_** of directives from Apache **_2.2_** to **_2.4_**.
The **_absence_** of **_mod_authz_host_** does not define to be on **_Apache 2.4_**.
**_mod_access_compat_** was introduced with apache **_2.3_** to keep **_OLD mod_authz_host_** directives (**_Order_**) without the need to change to the **_NEW mod_authz_host_** directives (**_Require_**).
On **_Apache 2.2_**: **mod_authz_host** is using the **_Order_** directive.
See also:
https://httpd.apache.org/docs/2.2/mod/mod_authz_host.html
On **_Apache 2.4_**: **mod_authz_host** is using the **_Require_** directive.
See also:
https://httpd.apache.org/docs/2.4/mod/mod_authz_host.html

So if you want a working solution that can still be used on **_OLD Apache 2.2_** as well as on **_Apache 2.4_** then just take my PR **_as is_**.
If you want a correct and working solution **_only_** for **_Apache 2.4_** convert all your **_OLD_** **_Order_** directives to the **_NEW_** **_Require_** directive.

If you still don't understand then just close this PR. I am tired.

**Comment by shreesh-webkul** [comment]
@computersalat 

We have checked the issue does occur in openSESU 15.3 but it took some time to recreate the issue as the complete steps were not clear on how the recreate the issue and the testing environment.

The "mod_access_compat" directives have been deprecated in apache 2.4 by "mod_authz_host".
Please see the warning in https://httpd.apache.org/docs/2.4/mod/mod_access_compat.html
So it is now encouraged to use mod_authz_host.

we need the code that is being merged with QloApps to be of the correct standard.
Please update the PR, we are waiting.

**Comment by computersalat** [comment]
@shreesh-webkul

You still didn't answer the question about what you want.
Read my previous comment carefully and answer the question for yourself.
If you know what you want then proceed as proposed.

**Comment by computersalat** [comment]
@shreesh-webkul
All your `.htaccess` files consists of the **OLD Order** Directives that should be used by **Apache 2.2**.

Note
```
The directives provided by [mod_access_compat](https://httpd.apache.org/docs/2.4/mod/mod_access_compat.html) have been deprecated by [mod_authz_host](https://httpd.apache.org/docs/2.4/mod/mod_authz_host.html).
Mixing old directives like [Order](https://httpd.apache.org/docs/2.4/mod/mod_access_compat.html#order), [Allow](https://httpd.apache.org/docs/2.4/mod/mod_access_compat.html#allow)
 or [Deny](https://httpd.apache.org/docs/2.4/mod/mod_access_compat.html#deny) with new ones like [Require](https://httpd.apache.org/docs/2.4/mod/mod_authz_core.html#require) is technically possible but discouraged.
This module was created to support configurations containing only old directives to facilitate the 2.4 upgrade. Please check the [upgrading](https://httpd.apache.org/docs/2.4/upgrading.html) guide for more information.
```
If you want to continue using your **old code** also on **Apache >= 2.4** then you **must use mod_access_compat** because you don't know if the guy that is running apache 2.4 is using **mod_access_compat** or not.
If that guy is not using **mod_access_compat** on his apache 2.4, then you **must use** the **NEW Require** Directive.

This patch is perfect for using the code on **Apache 2.2** as well as on **Apache 2.4**. No matter if **mod_access_compat** is being used on **Apache 2.4** or not.

Hopefully you will understand now.

**Comment by rohit053** [comment]
We have updated .htaccess files compatibility with Apache 2.2 and 2.4 in the PR #1062 . So, we are closing this PR.

**Pull request closed without merging**
