### PR TITLE
Fix: initToolbar

### PR DESCRIPTION
**Pull request by wdammak**

### CODE REVIEW

**Comment by shreesh-webkul** [comment]
In outsanding page, the `initToolbar` is overrided to hide add button in list toolbar.
This PR adds the button back which is not required as there are no forms in this page

**Comment by wdammak** [comment]
So why i have this error?:
Notice on line 2643 in file \www\hotelcommerce\classes\controller\AdminController.php
[8] Undefined property: AdminOutstandingController::$toolbar_btn

**Comment by shreesh-webkul** [comment]
We are not able to recreate the issue, please provide us with steps to recreate the issue. 
Also, please provide us with the PHP version you are running.

**Comment by wdammak** [comment]
> 

php7.4.10

once I remove this line (parent::initToolbar();) I systematically have this warning
[8] Undefined property: AdminOutstandingController::$toolbar_btn

**Comment by shreesh-webkul** [comment]
The issue is coming from the Admin controller, we are updating the controller through which this issue will be resolved.

**Comment by wdammak** [comment]
thank  you @shreesh-webkul

**Pull request closed without merging**
