### PR TITLE
Replace mcrypt with openssl

### PR DESCRIPTION
**Pull request by shreesh-webkul**
Use openssl instead of mcrypt.
Added defuse library to manage cypher.
minimum PHP version now bumped to 5.6

### CODE REVIEW

**Comment by wdammak** [comment]
$this->mobile_detect = new \Mobile_Detect();
Fatal error: Uncaught Error: Class 'Mobile_Detect'
when I put the old code back it works:
require_once(_PS_TOOL_DIR_.'mobile_Detect/Mobile_Detect.php');
$this->mobile_detect = new Mobile_Detect();

**Comment by wdammak** [comment]
to delete : define('_PS_PEAR_XML_PARSER_PATH_',  _PS_TOOL_DIR_.'pear_xml_parser/');

**Comment by shreesh-webkul** [comment]
> $this->mobile_detect = new \Mobile_Detect();
> Fatal error: Uncaught Error: Class 'Mobile_Detect'
> when I put the old code back it works:
> require_once(_PS_TOOL_DIR_.'mobile_Detect/Mobile_Detect.php');
> $this->mobile_detect = new Mobile_Detect();

@wdammak 
The mobile detect code was not changed in this PR, We will resolve this with updates in composer.

**Comment by shreesh-webkul** [comment]
> to delete : define('_PS_PEAR_XML_PARSER_PATH_', _PS_TOOL_DIR_.'pear_xml_parser/');

Will check this and update accordingly.

**Comment by shreesh-webkul** [comment]
Fixed pear xml issue #268

**Comment by shreesh-webkul** [comment]
Closing due to duplicate #269

**Pull request closed without merging**
