### PR TITLE
Adding composer.json file and libraries are updated with composer

### PR DESCRIPTION
**Pull request by sumitwebkul**
- composer.json file added
- Below libraries are updated with the composer
1. swiftmailer
2. archive_tar
3. tcpdf
4. mobiledetectlib
5. xml_feed_parser
6. http_build_url
7. htmlpurifier
- composer.lock file added

### CODE REVIEW

**Comment by wdammak** [comment]
There is something I don't understand!
On the one hand you have just integrated composer and in other Pull Request you continue to update the libs in /tools/ *
!?

**Comment by sumitwebkul** [comment]
This is an incomplete PR. In the next release, we are not going to manage libraries with the composer. 
So we are closing this PR for now. But we will definitely do it in our future roadmaps.
Thanks.

**Comment by wdammak** [comment]
It’s a shame! you got to 99% progress then undo ?! 
Personally I was able to run it with compose based on your PR without any problem!

The problem that your PR does not merge in the develop branch so it's painful to go ahead and test! 
in the develop branch normally everything is allowed even rollbacks.

**Comment by sumitwebkul** [comment]
@wdammak 

Don't worry, this code is not going to be wasted. Because of some reasons we are not doing it in the next version. 
We will soon make all the libraries and other things compatible with the composer.

Thanks

**Pull request closed without merging**
